### ISSUE TITLE
Dungeon doesn't generate properly using anything other than the Static Mesh Generation Method

### ISSUE THREAD

**Issue by obsidiousdev** [shun126/UE5-DungeonGeneratorDemo#55] opened 2024-09-17 05:08 UTC
**Describe the bug**
In my level, which is infinitely generated using Procedural Terrain, I generate the dungeon 1000 units below my character and teleport them inside. When I have the dungeon set to generate using Static Meshes, this all works, but pathways and rooms, generally, the entire dungeon (except for the prefab rooms) fail to generate. This is the only mode that generates Props and Interior Database actors, too. When I set the Generation Method to Hierarchichal or Instanced Static Mesh, the dungeon generates properly but none of the Props or Interior Database actors do.

**To Reproduce**
1. Set Dungeon Generation Method to Hierarchical or Instanced mode
2. Assign Interior database actors and whatnot
3. Generate the dungeon during runtime and teleport the player to the starting room

**Expected behavior**
I assume the expected behavior is that the dungeon generates across all 3 of these modes equally, with it being up to the user to choose which one they'd like to go with. For me though, Static Mesh generation doesn't work for the dungeon meshes (like hallways and rooms) but its the only mode Props spawn in.

**Screenshots**
Upon setting the method to Static Mesh and attempting to play a dungeon generation.. After I'm done playing I see this pop up in the console
![image](https://github.com/user-attachments/assets/e39cab59-acf0-42d1-b6af-4d9b886e7731)

STATIC MESH GENERATION METHOD
![image](https://github.com/user-attachments/assets/e956e5c5-8419-4916-b9e8-67a2510eb446)

INSTANCED STATIC MESH GENERATION METHOD (notice how there's ZERO props or interior actors apart from Lights)
![image](https://github.com/user-attachments/assets/4d037fa5-e0d7-4012-855e-05dc8eb0a8a0)

**Environment (please complete the following information):**
 - OS: Windows
 - Unreal Engine V5.3
 - Plugin Version 1.6.6

**Comment by shun126** [comment] 2024-09-21 05:24
I apologize for the inconvenience.

The issue where Props and Interior Database actors were not generated when set to Hierarchical or Instanced Static Mesh has been fixed in version 1.6.7.
(Note: version 1.6.7 is currently under review.)

I will investigate other issues related to dungeon generation during runtime.

**Comment by shun126** [comment] 2024-09-27 01:12
I have identified the cause. It has been fixed in version 1.6.8, which I have submitted to Epic. I apologize for the inconvenience and kindly ask for your patience a little longer.

**Comment by shun126** [comment] 2024-09-30 15:27
I sincerely apologize for the wait. Version 1.6.9 has been approved. Please update the plugin.

**Comment by obsidiousdev** [comment] 2024-10-04 09:16
Thank you very much! I hope it isn't a bother, but is it a known issue that Static Mesh mode doesn't work? It calls hundreds of errors saying "Called set static mesh on (...) but its Mobility is Static." and results in the dungeon not being properly generated. At least, for me... It's unfortunate too, because Instanced and Heirarchical both work on the host end but do not replicate, as I can see looking under the hood. Static Mesh generation seems to only work when generated before starting the game or at the same time, while not working when done at runtime. Also, the alternate generate modes do not replicate when done at runtime. Please see if you can fix this <3
As always, I love your plugin so much

**Comment by shun126** [comment] 2024-10-04 17:08
If it is a single player, I think it has been fixed in version 1.6.9.
I did not test dungeon generation while connected to the network. sorry.

**Closed** 2024-10-12 08:26 UTC
Labels: bug, doing
